### ISSUE TITLE
Image / code popup opens then closes immediatly on first click - text loses focus

### ISSUE THREAD

**Issue by trompx** [Canner/canner-slate-editor#17]
When selecting text then clicking on image or code buttons, the popup opens then closes immediatly on first click. On second click the popup stays but the text lost the focus. 
So if I selected 3 lines to set CSS code, only the first line get the style.

**Comment by chilijung** [comment]
fix in latest version, thanks

**Comment by trompx** [comment]
Ok, I did not run it locally, just tested on your demo site. To prevent opening further already corrected issues, do you have an auto deploy of the last master code to your live demo site?

**Comment by chilijung** [comment]
@trompx sorry my bad, I thought I fix it, but find out still not working... I'll try to fix it. Thanks.

**Comment by chilijung** [comment]
@trompx This is fixed in the new version, thanks for mentioning the issue.

**Comment by chilijung** [comment]
Also, the demo page is updated, you could try it online.

**Comment by trompx** [comment]
Hey @chilijung,

Just tested your new release.
The first click issue is gone.
But when selecting multiple lines then click on code, it still only apply to the first line.

**Comment by chilijung** [comment]
@trompx Oh, I haven't implemented to allow users to apply code block for multiple lines. But I'll do it later, open [an issue here](https://github.com/Canner/slate-editor-icons/issues/60) to solve this issue.
