### ISSUE TITLE
Writing multiple ´-characters make the editor freeze.

### ISSUE THREAD

**Issue by tormodvm** [Canner/canner-slate-editor#22]
I tried the live demo [here](https://canner.github.io/slate-md-editor/) and accidentally typed in a couple of ´-characters at the start of a header. The editor froze and I couldn't delete it.

**Comment by trompx** [comment]
Just confirmed that. Opening the devtools performance shows (on my computer : i7) 1 keypress takes 40-80ms with a really deep tree of (value).

**Comment by chilijung** [comment]
I think this is because our demo is generating and parsing HTML syntax(prism) in realtime. I didn't take time to optimize our demo.

https://github.com/Canner/slate-md-editor/blob/master/docs/App.js#L28-L30

**Comment by chilijung** [comment]
Please try in the latest version, I think this is no longer an issue! https://canner.github.io/canner-slate-editor/?selectedKind=canner-slate-editor&selectedStory=Simple&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
