### ISSUE TITLE
Keep getting module not found

### ISSUE THREAD

**Issue by gagandeepgill** [Canner/canner-slate-editor#26]
![image](https://user-images.githubusercontent.com/8551508/40005895-141168a6-5767-11e8-8257-b5d157a85ae0.png)

![image](https://user-images.githubusercontent.com/8551508/40005935-2843ba5e-5767-11e8-9421-846c68c30b5c.png)

I followed your instructions on installing and implementation. But this is the error I get,

I am using create-react-app with npm run eject

**Comment by chilijung** [comment]
Fix in 0.4.2 version ! Please try and confirm! Thanks!

**Comment by gagandeepgill** [comment]
Just had to change `slate-icon-codeBlock` to `slate-icon-codeblock`
`\node_modules\@canner\slate-icon-codeBlock\lib\index.js` does not match the corresponding path on disk `slate-icon-codeblock`.`
