### ISSUE TITLE
Image upload 'Sorry, there was a problem with your request'

### ISSUE THREAD

**Issue by gagandeepgill** [Canner/canner-slate-editor#27]
Amazing work you have done with the editor. It is really sleek and well done! Just wondering if there is a way to remove or add tabs to the image modal?

![image](https://user-images.githubusercontent.com/8551508/40664002-ebcf8fcc-6327-11e8-8d28-0b067884aea5.png)

Also, I tried to upload images to the upload tab but I keep getting 'Sorry, there was a problem with your request'. I looked through the documentation but I could not seem to find anything related image upload.

**Comment by chilijung** [comment]
@gagandeepgill, you will need to pass a `serviceConfig` prop to make it work. I've added a section in readme https://github.com/Canner/canner-slate-editor#image-upload. Please take a look!

**Comment by gagandeepgill** [comment]
@chilijung Thanks! I've taken a look at it. gotten the clientId, clientSecret and what not from postman. Even changed the headers to my client id. But still the same issue, maybe I'm implementing it wrong? I was wondering if you could guide me through it if possible :)

`
import {ImgurService} from '@canner/image-service-config';
...
const imageService = new ImgurService({
  clientId: 'my client id', 
});

const serviceConfig = imageService.getServiceConfig();
...
render() {
    const {value} = this.state;
return (
           <CannerEditor
                value={value}
                onChange={this.onChange}
                plugins={plugins}
                {...serviceConfig}
            />
  );
}
`

**Comment by chilijung** [comment]
You also need a `mashapeKey` : https://github.com/Canner/image-service-config#args

**Comment by chilijung** [comment]
And you just pass your `serviceConfig` as props

```js
<CannerEditor
                value={value}
                onChange={this.onChange}
                plugins={plugins}
                serviceConfig={serviceConfig}
            />
```

**Comment by gagandeepgill** [comment]
@chilijung Thanks for the help! Just wondering since I'm still learning, is there a way to upload locally instead of using imgur/other services? Also is there a way to removed the tabs in the upload button?

![image](https://user-images.githubusercontent.com/8551508/40789363-3f1464e8-64c0-11e8-8b46-1497430f617f.png)

**Comment by ShawTim** [comment]
+1 for this question.

**Comment by chilijung** [comment]
Hi, @gagandeepgill  @ShawTim 

`Image` is working in version `0.5.0`, please try the latest version.

- Image upload in broken in previous versions, fix in this issue: https://github.com/Canner/canner-slate-editor/pull/29
- Yes, you can set up your own gallery if you want to remove it just pass `null` into prop `galleryConfig`,  if you want to replace with your own gallery images see how to set up here: https://github.com/Canner/image-upload/blob/master/src/config.js

Thanks!
