### ISSUE TITLE
Using shortcut keys will enter the shortcuts into the editor.

### ISSUE THREAD

**Issue by IceEnd** [Canner/canner-slate-editor#32]
For example, when I type `ctrl+opt+1`, the editor inserts ‘1’.

 The `keyDown` listener event should block the default event:`e.preventDefault();`

Many of `slate` plugins are managed using npm. How should we create a PR?

**Comment by chilijung** [comment]
@IceEnd I've fixed this issue, you could try out here https://canner.github.io/canner-slate-editor/?selectedKind=slate-md-editor&selectedStory=Simple&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Also for more easy for maintaining modules, I've restructured the whole project to a single repo! https://github.com/Canner/canner-slate-editor
